In [1]:
import pandas as pd

# 1. Panggil data bersih yang kemarin udah kita save!
df = pd.read_csv('startup_cleaned.csv')

# 2. Ubah kolom 'founded_at' yang tadinya cuma teks biasa jadi format WAKTU (Datetime) beneran
df['founded_at'] = pd.to_datetime(df['founded_at'], errors='coerce')

# 3. MENCIPTAKAN FITUR BARU: Umur Startup!
# (Dataset Crunchbase ini direkam sekitar akhir tahun 2015, jadi kita pakai 2015 sebagai patokan umur)
df['umur_startup_tahun'] = 2015 - df['founded_at'].dt.year

# 4. Intip hasilnya!
df[['name', 'founded_at', 'umur_startup_tahun']].head(10)

                 name founded_at  umur_startup_tahun
0            #waywire 2012-06-01                 3.0
1  &TV Communications        NaT                 NaN
2   'Rock' Your Paper 2012-10-26                 3.0
3   (In)Touch Network 2011-04-01                 4.0
4  -R- Ranch and Mine 2014-01-01                 1.0
5       .Fox Networks        NaT                 NaN
6             0-6.com 2007-01-01                 8.0
7    004 Technologies 2010-01-01                 5.0
8  01Games Technology        NaT                 NaN
9         1,2,3 Listo 2012-01-01                 3.0

In [2]:
# 1. Buang startup yang umur atau total pendanaannya kosong (NaN)
df = df.dropna(subset=['umur_startup_tahun', 'funding_total_usd'])

# 2. Pilih "Tim Inti" (Fitur) yang mau kita ajarin ke AI
fitur_pilihan = ['funding_total_usd', 'funding_rounds', 'umur_startup_tahun', 'status']
df_final = df[fitur_pilihan].copy()

# 3. TRANSLASI BAHASA AI! Ubah target teks jadi angka
# Bangkrut (closed) = 0, Sukses (acquired) = 1, Masih Jalan (operating) = 2
status_map = {'closed': 0, 'acquired': 1, 'operating': 2}
df_final['target'] = df_final['status'].map(status_map)

# Buang kolom status lama yang masih bentuk teks
df_final = df_final.drop(columns=['status'])

# Intip bentuk akhir data kita sebelum dimasukin ke mesin AI
print("Jumlah data siap tempur:", df_final.shape)
df_final.head()

Jumlah data siap tempur: (31441, 4)

   funding_total_usd  funding_rounds  umur_startup_tahun  target
0          1750000.0             1.0                 3.0       1
2            40000.0             1.0                 3.0       2
3          1500000.0             1.0                 4.0       2
4            60000.0             2.0                 1.0       2
6          2000000.0             1.0                 8.0       2

In [3]:
# Save data yang udah jadi angka semua ini!
df_final.to_csv('startup_ml_ready.csv', index=False)

print("Data ML-Ready berhasil disave! AI siap dilatih! 🤖💾")

Data ML-Ready berhasil disave! AI siap dilatih! 🤖💾